name: 'Setup OpenModelica environment'
description: 'Set up a OpenModelica environment and add it to the PATH'
author: 'Andreas Heuermann'
inputs:
  version:
    description: 'The OpenModelica version to use.
                  Example: "1.19.0" for version 1.19.0
                           or "" for latest release version'
    required: false
    default: 'release'
  architecture: 
    description: 'The architecture of OpenModelica to be used.
                  Can be "64" or "32".'
    required: false
    default: '64'
  packages:
    description: 'Optional list of OpenModelica APT packages to install.
                  Each package has to be in a new line. Ignored on Windows.'
    required: false
    default: 'omc'
  libraries:
    description: 'Optional list of Modelica libraries to install.
                  One library per line, separate version number with a space <library> <version>
                  Example: "Modelica 4.0.0"'
    required: false
  omc-diff:
    description: 'Install OpenModelica omc-diff tool.'
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'download'
  color: 'blue'
