name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  repository_dispatch:
    types: [dependabot-dist-updated]

jobs:
  build: # make sure build/ci works properly
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set Node.js 24.x
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.x

      - name: Install
        run: npm install

      - name: Check Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Package
        run: npm run package

      - name: Jest Test
        run: npm run test

  test: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [stable, '1.25']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./
        with:
          version: ${{ matrix.version }}
          packages: |
            'omc'
            'omsimulator'
          libraries: |
            'Modelica 4.1.0'
            'Modelica 3.2.3+maint.om'
          omc-diff: true
      - run: echo $OPENMODELICAHOME
